export const ACE_LAB_LEVELS = [
  {
    id: "1-3",
    label: "Levels 1–3",
    course: "Science foundations",
    basis: "Observation-first science: materials, changes, and safe comparison.",
  },
  {
    id: "4-6",
    label: "Levels 4–6",
    course: "Intermediate Science",
    basis: "ACE guidance recommends regular practical work using grade-level science experiment notes.",
  },
  {
    id: "7-9",
    label: "Levels 7–9",
    course: "General Science",
    basis: "ACE practical progression includes particles, atoms, elements, compounds, diffusion, and acid–metal reactions.",
  },
  {
    id: "10",
    label: "Level 10",
    course: "Physical Science",
    basis: "ACE Physical Science practical work prepares learners for reaction, measurement, and energy investigations.",
  },
  {
    id: "11",
    label: "Level 11",
    course: "Chemistry · PACEs 1121–1132",
    basis: "Published ACE objectives include reactions, equations, acids and bases, phases, bonding, and the periodic table.",
  },
  {
    id: "extension",
    label: "Chemistry extension",
    course: "Advanced practical enrichment",
    basis: "Optional enrichment; ACE Level 12’s standard science course is Physics, not Chemistry.",
  },
];

export const ACE_LAB_EXPERIMENTS = [
  {
    id: "states-observation",
    level: "1-3",
    title: "Solid, liquid, or gas?",
    kind: "guided",
    duration: "8 min",
    apparatus: ["sealed sample cards", "observation tray"],
    steps: ["Compare shape and flow.", "Sort each sample by state.", "Explain what changed and what stayed the same."],
    observation: "Solids retain shape; liquids flow and retain volume; gases fill their container.",
    safety: "Use sealed, classroom-safe samples only.",
  },
  {
    id: "dissolve-recover",
    level: "1-3",
    title: "Dissolve and recover salt",
    kind: "guided",
    duration: "12 min",
    apparatus: ["water", "salt", "clear cup", "evaporation dish"],
    steps: ["Add salt to water.", "Stir and observe.", "Allow a prepared sample to evaporate and compare."],
    observation: "Salt seems to disappear during dissolving but can be recovered after water evaporates.",
    safety: "Do not taste laboratory materials.",
  },
  {
    id: "density-layers",
    level: "4-6",
    title: "Density layers",
    kind: "guided",
    duration: "15 min",
    apparatus: ["measuring cylinder", "water", "vegetable oil", "syrup"],
    steps: ["Measure equal volumes.", "Pour slowly into the cylinder.", "Record the order of the layers."],
    observation: "Denser liquids settle below less-dense liquids.",
    safety: "Wipe spills immediately.",
  },
  {
    id: "mixture-separation",
    level: "4-6",
    title: "Separate a mixture",
    kind: "guided",
    duration: "20 min",
    apparatus: ["sand", "salt", "water", "filter funnel", "evaporation dish"],
    steps: ["Dissolve the salt.", "Filter out the sand.", "Evaporate the filtrate to recover salt."],
    observation: "Different physical properties allow a mixture’s components to be separated.",
    safety: "Heating is teacher-controlled.",
  },
  {
    id: "diffusion",
    level: "7-9",
    title: "Diffusion in water",
    kind: "guided",
    duration: "12 min",
    apparatus: ["clear beakers", "warm and cold water", "food colouring"],
    steps: ["Prepare equal water volumes.", "Add one drop of colour to each.", "Compare spreading rates."],
    observation: "Particles spread faster in warmer water.",
    safety: "Use food-safe colouring and avoid splashes.",
  },
  {
    id: "acid-metal",
    level: "7-9",
    title: "Acid + metal gas test",
    kind: "guided",
    duration: "18 min",
    apparatus: ["zinc", "dilute hydrochloric acid", "test tube", "splint"],
    steps: ["Add zinc to dilute acid.", "Observe gas evolution.", "A teacher demonstrates the hydrogen pop test."],
    observation: "Zinc chloride and hydrogen form; hydrogen gives a squeaky pop.",
    safety: "Teacher supervision, eye protection, and small quantities are mandatory.",
  },
  {
    id: "indicator-range",
    level: "7-9",
    title: "Indicator colour range",
    kind: "guided",
    duration: "15 min",
    apparatus: ["spotting tile", "universal indicator", "labelled safe solutions"],
    steps: ["Place one drop of each solution.", "Add indicator.", "Match colours to the pH scale."],
    observation: "Indicators show whether a solution is acidic, neutral, or alkaline.",
    safety: "Use only teacher-approved dilute solutions.",
  },
  {
    id: "neutralisation-qualitative",
    level: "10",
    title: "Neutralisation by indicator",
    kind: "titration",
    duration: "20 min",
    titration: {
      analyte: "Dilute HCl",
      analyteFormula: "HCl",
      analyteM: 0.05,
      analyteMl: 20,
      analyteFactor: 1,
      titrant: "Dilute NaOH",
      titrantFormula: "NaOH",
      titrantM: 0.05,
      titrantFactor: 1,
      indicator: "Universal indicator",
      indicatorType: "universal",
      equation: "HCl + NaOH → NaCl + H₂O",
    },
    apparatus: ["burette", "conical flask", "measuring cylinder", "universal indicator"],
    steps: ["Measure acid into the flask.", "Add indicator.", "Add alkali slowly while swirling.", "Stop near green."],
    observation: "The indicator moves from acidic colours toward green at neutralisation.",
    safety: "Wear eye protection; use dilute solutions.",
  },
  {
    id: "reaction-rate",
    level: "10",
    title: "Concentration and reaction rate",
    kind: "guided",
    duration: "25 min",
    apparatus: ["sodium thiosulfate", "dilute acid", "marked paper", "timer"],
    steps: ["Prepare teacher-approved dilutions.", "Mix one pair.", "Time until the mark is obscured.", "Compare trials."],
    observation: "Higher concentration generally increases collision frequency and reaction rate.",
    safety: "Use small quantities in strong ventilation under teacher control.",
  },
  {
    id: "hcl-naoh",
    level: "11",
    title: "Strong acid–strong base titration",
    kind: "titration",
    duration: "30 min",
    titration: {
      analyte: "Hydrochloric acid",
      analyteFormula: "HCl",
      analyteM: 0.1,
      analyteMl: 25,
      analyteFactor: 1,
      titrant: "Sodium hydroxide",
      titrantFormula: "NaOH",
      titrantM: 0.1,
      titrantFactor: 1,
      indicator: "Phenolphthalein",
      indicatorType: "phenolphthalein",
      equation: "HCl + NaOH → NaCl + H₂O",
    },
    apparatus: ["50 mL burette", "25 mL pipette", "conical flask", "white tile"],
    steps: ["Rinse and fill the burette.", "Pipette 25.00 mL acid.", "Add indicator.", "Titrate to a permanent pale pink endpoint."],
    observation: "A faint pink colour persisting for about 30 seconds marks the endpoint.",
    safety: "Wear goggles; rinse splashes with plenty of water.",
  },
  {
    id: "ethanoic-naoh",
    level: "11",
    title: "Weak acid–strong base titration",
    kind: "titration",
    duration: "30 min",
    titration: {
      analyte: "Ethanoic acid",
      analyteFormula: "CH₃COOH",
      analyteM: 0.1,
      analyteMl: 25,
      analyteFactor: 1,
      titrant: "Sodium hydroxide",
      titrantFormula: "NaOH",
      titrantM: 0.1,
      titrantFactor: 1,
      indicator: "Phenolphthalein",
      indicatorType: "phenolphthalein",
      equation: "CH₃COOH + NaOH → CH₃COONa + H₂O",
    },
    apparatus: ["burette", "volumetric pipette", "conical flask", "white tile"],
    steps: ["Transfer the weak acid.", "Add phenolphthalein.", "Titrate while swirling.", "Approach the endpoint dropwise."],
    observation: "The suitable endpoint is the first persistent very pale pink.",
    safety: "Treat all solutions as laboratory chemicals.",
  },
  {
    id: "sulfuric-naoh",
    level: "11",
    title: "Diprotic acid titration",
    kind: "titration",
    duration: "35 min",
    titration: {
      analyte: "Sulfuric acid",
      analyteFormula: "H₂SO₄",
      analyteM: 0.05,
      analyteMl: 25,
      analyteFactor: 2,
      titrant: "Sodium hydroxide",
      titrantFormula: "NaOH",
      titrantM: 0.1,
      titrantFactor: 1,
      indicator: "Methyl orange",
      indicatorType: "methyl-orange",
      equation: "H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O",
    },
    apparatus: ["burette", "pipette", "conical flask", "methyl orange"],
    steps: ["Pipette the acid.", "Add methyl orange.", "Titrate with alkali.", "Use the mole ratio to calculate concentration."],
    observation: "The indicator changes through orange near the stoichiometric endpoint.",
    safety: "Use dilute acid and eye protection.",
  },
  {
    id: "redox-permanganate",
    level: "extension",
    title: "Permanganate redox titration",
    kind: "titration",
    duration: "40 min",
    titration: {
      analyte: "Acidified iron(II)",
      analyteFormula: "Fe²⁺",
      analyteM: 0.1,
      analyteMl: 25,
      analyteFactor: 1,
      titrant: "Potassium permanganate",
      titrantFormula: "MnO₄⁻",
      titrantM: 0.02,
      titrantFactor: 5,
      indicator: "Self-indicating",
      indicatorType: "permanganate",
      equation: "MnO₄⁻ + 5Fe²⁺ + 8H⁺ → Mn²⁺ + 5Fe³⁺ + 4H₂O",
    },
    apparatus: ["burette", "pipette", "conical flask", "dilute sulfuric acid"],
    steps: ["Prepare acidified iron(II).", "Titrate with permanganate.", "Swirl after every addition.", "Stop at a persistent pale pink."],
    observation: "The first permanent pale pink shows a slight excess of permanganate.",
    safety: "Advanced teacher-supervised practical only.",
  },
];

export function experimentsForLevel(level) {
  return ACE_LAB_EXPERIMENTS.filter((experiment) => experiment.level === level);
}

export function titrationState(experiment, deliveredMl) {
  const config = experiment?.titration;
  if (!config) return null;
  const analyteEq = config.analyteM * config.analyteMl * config.analyteFactor;
  const titrantEqPerMl = config.titrantM * config.titrantFactor;
  const endpointMl = analyteEq / titrantEqPerMl;
  const delivered = Math.max(0, Math.min(50, Number(deliveredMl) || 0));
  const ratio = endpointMl > 0 ? delivered / endpointMl : 0;
  let color = "#f8fafc";
  if (config.indicatorType === "phenolphthalein") {
    color = ratio < 0.985 ? "#f8fafc" : ratio <= 1.015 ? "#f9c5df" : "#ec4899";
  } else if (config.indicatorType === "methyl-orange") {
    color = ratio < 0.97 ? "#ef4444" : ratio <= 1.03 ? "#f97316" : "#facc15";
  } else if (config.indicatorType === "permanganate") {
    color = ratio <= 1 ? "#fff7ed" : ratio <= 1.03 ? "#f5b6d2" : "#a855f7";
  } else {
    color = ratio < 0.8 ? "#ef4444" : ratio < 0.98 ? "#f59e0b" : ratio <= 1.02 ? "#22c55e" : "#6366f1";
  }
  return {
    deliveredMl: delivered,
    endpointMl,
    ratio,
    color,
    atEndpoint: ratio >= 0.985 && ratio <= 1.02,
    pastEndpoint: ratio > 1.02,
  };
}
